Repository ts-graphviz/parser, pull requests merged in 2021-08, with the labels that each got.

#26 export convert method to allow downstream adopters to leverage it
  src/index.ts
Labels: enhancement

#25 docs: correct minor typo in readme
  README.md
Labels: documentation

#32 Add stringify function
  README.md
  grammar/dot.peggy
  img/state-machine.svg
  jest.config.ts
  package.json
  scripts/create-state-machine-diagram.ts
  src/__test__/__snapshots__/ast.test.ts.snap
  src/__test__/ast.test.ts
  src/ast.ts
  yarn.lock
Labels: documentation, enhancement
